[buildPlans.IosevkaMint]
family = "Iosevka Mint"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaMint.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-q = "straight"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
l = "serifed-flat-tailed"
r = "compact-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
y = "cursive-flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-iota = "serifed-flat-tailed"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
zero = "dotted"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
eight = "two-circles"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "open"
cent = "open"
question = "corner"
partial-derivative = "straight-bar"

[buildPlans.IosevkaMint.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-q = "straight"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
r = "compact-serifless"
t = "flat-hook"
u = "toothed-serifless"
y = "cursive-flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
zero = "dotted"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
eight = "two-circles"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "open"
cent = "open"
question = "corner"
partial-derivative = "straight-bar"

  [buildPlans.IosevkaMint.ligations]
  inherits = "javascript"

[buildPlans.IosevkaMint.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaMint.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaMintTerm]
family = "Iosevka Mint Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaMintTerm.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-q = "straight"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
l = "serifed-flat-tailed"
r = "compact-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
y = "cursive-flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-iota = "serifed-flat-tailed"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
zero = "dotted"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
eight = "two-circles"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "open"
cent = "open"
question = "corner"
partial-derivative = "straight-bar"

[buildPlans.IosevkaMintTerm.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-q = "straight"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
r = "compact-serifless"
t = "flat-hook"
u = "toothed-serifless"
y = "cursive-flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
zero = "dotted"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
eight = "two-circles"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "open"
cent = "open"
question = "corner"
partial-derivative = "straight-bar"

  [buildPlans.IosevkaMintTerm.ligations]
  inherits = "javascript"

[buildPlans.IosevkaMintTerm.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaMintTerm.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaMintSans]
family = "Iosevka Mint Sans"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaMintSans.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "serifless"
capital-j = "flat-hook-serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "straight"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifless"
j = "flat-hook-serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
r = "compact-serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
y = "cursive-flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-iota = "serifed-flat-tailed"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
zero = "dotted"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
eight = "two-circles"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
question = "corner"
partial-derivative = "straight-bar"

[buildPlans.IosevkaMintSans.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "flat-hook-serifless"
capital-k = "symmetric-connected-serifless"
capital-q = "straight"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "flat-tailed"
j = "flat-hook-serifless"
k = "symmetric-connected-serifless"
r = "compact-serifless"
t = "flat-hook"
u = "toothed-serifless"
y = "cursive-flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-tau = "flat-tailed"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
zero = "dotted"
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
eight = "two-circles"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
question = "corner"
partial-derivative = "straight-bar"

  [buildPlans.IosevkaMintSans.ligations]
  inherits = "javascript"

[buildPlans.IosevkaMintSans.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaMintSans.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
